spring.application.name=notes-app
spring.datasource.url=jdbc:h2:file:./notesdb
spring.datasource.driver-class-name=org.h2.Driver
spring.sql.init.mode=always
spring.data.jdbc.dialect=H2
spring.main.allow-bean-definition-overriding=true
spring.sql.init.mode=always
spring.security.user.name=Chima
spring.security.user.password=Password1@
spring.jpa.show-sql=true

server.port=8081