CREATE TABLE IF NOT EXISTS NOTES (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255),
    content TEXT,
    created_at TIMESTAMP,
    folder VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS REMINDERS (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255),
    content TEXT,
    due_date TIMESTAMP,
    created_at TIMESTAMP,
    folder VARCHAR(255)
);