CREATE TABLE IF NOT EXISTS NOTES (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255),
    content TEXT
);


CREATE TABLE IF NOT EXISTS REMINDERS (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255),
    content TEXT,
    due_date TIMESTAMP
);